Force destroy in makefile
verypossible/aws-starter-kit pull request #1
Opened 2018-05-18 14:01 UTC by bbrock25

Why:

* as it stands, destroy doesn't actually do anything

This change addresses the need by:

* update destroy command in makefile to use the --force flag

Are there any side effects?

* resources in aws will be killed ded

2018-05-21 15:15 UTC, squaresurf approved these changes
You could check an env var if you wanted to ensure that folks don't accidentally destroy things. Not necessary though :)

2018-05-21 17:15 UTC, squaresurf requested changes
After re-review, I can see that you could use `${ARGS}` to ensure that folks wanting to destroy would need to pass the flag like so `ARGS="--force" make destroy`. I think that sort of protection would be a good thing to have so long as we have documentation letting people know how to destroy :smile:.

2018-05-22 18:31 UTC, bbrock25 commented
@squaresurf I like that approach. Will adjust.

2018-05-23 15:01 UTC, brianz commented
Yeah...this can be done as @squaresurf recommends:

```bash
make destroy STACK=staging ARGS=--force
```

2018-05-23 15:01 UTC, closed without merging